name: mydumper # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: 'v0.15.2-6' # just for humans, typically '1.2+git' or '1.3.2'
summary: MyDumper is a MySQL Logical Backup Tool # 79 char long summary
description: |
  MyDumper is a MySQL Logical Backup Tool. It has 2 tools:

      - **mydumper** which is responsible to export a consistent backup of MySQL databases
      - **myloader** reads the backup from mydumper, connects the to destination database and imports the backup.

  Both tools use multithreading capabilities.
  MyDumper is Open Source and maintained by the community, it is not a Percona, MariaDB or MySQL product.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  mydumper:
    command: mydumper

  myloader:
    command: myloader

architectures:
  - build-on: amd64

parts:
  mydumper:
    plugin: dump
    source: https://github.com/mydumper/mydumper
    source-type: git
    source-tag: 'v0.15.2-6'
    build-packages:
      - cmake
      - libglib2.0-dev
      - zlib1g-dev
      - libpcre3-dev
      - libssl-dev
      - libzstd-dev
      - libmysqlclient-dev
    override-build: |
      cmake .
      make
      cp $CRAFT_PART_BUILD/mydumper $CRAFT_PART_INSTALL/
      cp $CRAFT_PART_BUILD/myloader $CRAFT_PART_INSTALL/
